### PR TITLE
Change app name

### PR DESCRIPTION
**Pull request by timhot**
Most of the changes are due to moving the files to a different package 'birdmonitor'

Before I tried to merge this branch, I also allowed Android Studio to upgrade Gradle on my PC which I think may have also resulted in lots of 'tidying up' of my code.  Not sure if this is why I now get the message above "Can't automatically merge".  Not sure what that now means for merging?  Anyway, this code does work on my phone!

Suggestions very welcome.

### CODE REVIEW

**Comment by mjs** [comment]
With this branch checked out on your machine, try `git pull --rebase origin/master`.

That will re-apply these changes on top of the current master branch on Github. There will probably be some conflicts which you'll have to manually fix. When there's a conflict Git will pause the rebase. You then manually fix the conflicts (in a text editor or IDE) and `git add` the fixed up files. When all conflicts are fixed use `git rebase --continue` to continue the rebase. If there's multiple commits to apply then these pause-fix-continue steps can happen multiple times.

When the rebase is done, `git push -f origin HEAD:change_app_name` to update the rename PR on Github.

If you get stuck I can probably do the rebase for you.

**Comment by timhot** [comment]
I'm feeling useless :-(  Here is what I tried

(base) tim@Unix1:~/StudioProjects/cacophonometer2/birdmonitor$ git checkout change_app_name
Switched to branch 'change_app_name'
Your branch is up to date with 'origin/change_app_name'.
(base) tim@Unix1:~/StudioProjects/cacophonometer2/birdmonitor$ git pull --rebase origin/master
fatal: 'origin/master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(base) tim@Unix1:~/StudioProjects/cacophonometer2/birdmonitor$ git remote -v
origin  https://github.com/TheCacophonyProject/cacophonometer.git (fetch)
origin  https://github.com/TheCacophonyProject/cacophonometer.git (push)
(base) tim@Unix1:~/StudioProjects/cacophonometer2/birdmonitor$

**Comment by timhot** [comment]
OK, I figured that I should have a space rather than / between origin_master.  BUT what next?

(base) tim@Unix1:~/StudioProjects/cacophonometer2/birdmonitor$ git pull --rebase origin master
From https://github.com/TheCacophonyProject/cacophonometer
 * branch            master     -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: Changed app name from Cacophonomter to Bird Monitor.
Using index info to reconstruct a base tree...
M       app/build.gradle
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/CreateAccount.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/DeleteRecordings.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/GuiControls.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/HelperCode.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/Record.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/RegisterPhone.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/Rooted.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/RunAllTests.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/RunCreateAccount.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/RunDeleteRecordings.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/RunGuiControls.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/RunRecordSaveOnPhone.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/RunRecordSaveOnServer.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/RunRegisterPhone.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/RunRooted.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/RunSignInUser.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/RunUnRegisterPhone.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/RunUploadRecordings.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/SignInUser.java
M       app/src/androidTest/java/nz/org/cacophony/cacophonometer/UploadRecordings.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/AdvancedWizardActivity.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/AudioSourceSettingsFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/BatteryFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/CreateAccountFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/DisableActivity.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/ExecuteAsRootBase.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/FrequencyFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/GPSFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/GroupsFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/IdlingResourceForEspressoTesting.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/InternetConnectionFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/LocationReceiver.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/MainActivity.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/MainThread.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/ManageRecordingsFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/Prefs.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/RecordAndUpload.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/RegisterFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/RootedFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/SectionsStatePagerAdapter.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/Server.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/SetupWizardActivity.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/SignInFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/SoundFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/TestRecordFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/TestingFragment.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/Util.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/VitalsActivity.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/WalkingActivity.java
M       app/src/main/java/nz/org/cacophony/cacophonometer/WelcomeFragment.java
M       app/src/main/res/layout/activity_advance_wizard.xml
M       app/src/main/res/layout/activity_disable.xml
M       app/src/main/res/layout/activity_main2.xml
M       app/src/main/res/layout/activity_setup_wizard.xml
M       app/src/main/res/layout/activity_vitals.xml
M       app/src/main/res/layout/activity_walking.xml
M       app/src/main/res/layout/fragment_audio_source_settings.xml
M       app/src/main/res/layout/fragment_battery.xml
M       app/src/main/res/layout/fragment_frequency.xml
M       app/src/main/res/layout/fragment_groups.xml
M       app/src/main/res/layout/fragment_manage_recordings.xml
M       app/src/main/res/layout/fragment_register.xml
M       app/src/main/res/layout/fragment_rooted.xml
M       app/src/main/res/layout/fragment_sound.xml
M       app/src/main/res/layout/fragment_testing.xml
M       app/src/main/res/values/strings.xml
M       build.gradle
.git/rebase-apply/patch:5957: trailing whitespace.
           
.git/rebase-apply/patch:12668: new blank line at EOF.
+
.git/rebase-apply/patch:12856: new blank line at EOF.
+
warning: 3 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging app/src/main/res/values/strings.xml
Auto-merging app/src/main/res/layout/fragment_testing.xml
CONFLICT (content): Merge conflict in app/src/main/res/layout/fragment_testing.xml
Auto-merging app/src/main/res/layout/fragment_sound.xml
Auto-merging app/src/main/res/layout/fragment_rooted.xml
Auto-merging app/src/main/res/layout/fragment_register.xml
Auto-merging app/src/main/res/layout/fragment_manage_recordings.xml
Auto-merging app/src/main/res/layout/fragment_groups.xml
Auto-merging app/src/main/res/layout/fragment_frequency.xml
Auto-merging app/src/main/res/layout/fragment_battery.xml
Auto-merging app/src/main/res/layout/fragment_audio_source_settings.xml
Auto-merging app/src/main/res/layout/activity_walking.xml
Auto-merging app/src/main/res/layout/activity_vitals.xml
Auto-merging app/src/main/res/layout/activity_setup_wizard.xml
Auto-merging app/src/main/res/layout/activity_main2.xml
Auto-merging app/src/main/res/layout/activity_disable.xml
Auto-merging app/src/main/res/layout/activity_advance_wizard.xml
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/package-info.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/WelcomeFragment.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/WelcomeFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/WalkingActivity.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/VitalsActivity.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/Util.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/TestingFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/TestRecordFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/StartRecordingReceiver.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/SoundFragment.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/SoundFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/SignInFragment.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/SignInFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/SetupWizardActivity.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/SetupWizardActivity.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/Server.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/Server.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/SectionsStatePagerAdapter.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/RootedFragment.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/RootedFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/RegisterFragment.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/RegisterFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/RecordAndUpload.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/Prefs.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/MultipartUtility.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/ManageRecordingsFragment.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/ManageRecordingsFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/MainThread.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/MainService.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/MainActivity.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/LocationReceiver.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/LocationReceiver.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/InternetConnectionFragment.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/InternetConnectionFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/IdlingResourceForEspressoTesting.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/GroupsFragment.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/GroupsFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/GPSLocationListener.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/GPSFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/FrequencyFragment.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/FrequencyFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/ExecuteAsRootBaseTim.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/ExecuteAsRootBase.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/DisableActivity.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/DisableActivity.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/DawnDuskAlarms.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/CreateAccountFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/BootReceiver.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/BatteryFragment.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/BatteryFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/AudioSourceSettingsFragment.java
CONFLICT (content): Merge conflict in app/src/main/java/nz/org/cacophony/birdmonitor/AudioSourceSettingsFragment.java
Auto-merging app/src/main/java/nz/org/cacophony/birdmonitor/AdvancedWizardActivity.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/UploadRecordings.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/SignInUser.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/RunUploadRecordings.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/RunUnRegisterPhone.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/RunSignInUser.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/RunRooted.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/RunRegisterPhone.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/RunRecordSaveOnServer.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/RunRecordSaveOnPhone.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/RunGuiControls.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/RunDeleteRecordings.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/RunCreateAccount.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/RunAllTests.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/Rooted.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/RegisterPhone.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/Record.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/HelperCode.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/GuiControls.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/DeleteRecordings.java
Auto-merging app/src/androidTest/java/nz/org/cacophony/birdmonitor/CreateAccount.java
Auto-merging app/build.gradle
error: Failed to merge in the changes.
Patch failed at 0001 Changed app name from Cacophonomter to Bird Monitor.
Use 'git am --show-current-patch' to see the failed patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

**Comment by timhot** [comment]
Making progress.

I used Android Studio to list all files with conflicts, and opened each up in turn and accepted the 'change_app_name' version for each one, had to do this twice as you suggested might happen).  Then I ran git rebase --continue as shown next:

(base) tim@Unix1:~/StudioProjects/cacophonometer2/birdmonitor$ git rebase --continue
Applying: Changed app name from Cacophonomter to Bird Monitor.
(base) tim@Unix1:~/StudioProjects/cacophonometer2/birdmonitor$ git push -f origin HEAD:change_app_name
Username for 'https://github.com': timhot
Password for 'https://timhot@github.com': 
Counting objects: 112, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (99/99), done.
Writing objects: 100% (112/112), 85.10 KiB | 4.48 MiB/s, done.
Total 112 (delta 57), reused 0 (delta 0)
remote: Resolving deltas: 100% (57/57), completed with 29 local objects.
To https://github.com/TheCacophonyProject/cacophonometer.git
 + 5ab1f91...84265a4 HEAD -> change_app_name (forced update)
(base) tim@Unix1:~/StudioProjects/cacophonometer2/birdmonitor$ 

All looks good.  BUT on On GitHub, the master branch says that the last commit was 2 days ago, I would have expected it to say a couple of minutes ago.

**** Ah, just noticed that it said I can now merge! I did and it looks good :-)
Thanks Menno.

**Comment by mjs** [comment]
@timhot Nice work getting it sorted. 

Regarding the confusing commit timestamps, I wonder if a rebase preserves the original timestamps of the commits.

**Pull request merged**
